// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: course.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCourseListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int32                  `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseListRequest) Reset() {
	*x = GetCourseListRequest{}
	mi := &file_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseListRequest) ProtoMessage() {}

func (x *GetCourseListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseListRequest.ProtoReflect.Descriptor instead.
func (*GetCourseListRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{0}
}

func (x *GetCourseListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetCourseListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetCourseListRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetCourseListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List          []*CourseInfo          `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseListResponse) Reset() {
	*x = GetCourseListResponse{}
	mi := &file_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseListResponse) ProtoMessage() {}

func (x *GetCourseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseListResponse.ProtoReflect.Descriptor instead.
func (*GetCourseListResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{1}
}

func (x *GetCourseListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCourseListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCourseListResponse) GetList() []*CourseInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetCourseListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCourseDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseDetailRequest) Reset() {
	*x = GetCourseDetailRequest{}
	mi := &file_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseDetailRequest) ProtoMessage() {}

func (x *GetCourseDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseDetailRequest.ProtoReflect.Descriptor instead.
func (*GetCourseDetailRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{2}
}

func (x *GetCourseDetailRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type GetCourseDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CourseDetail  *CourseDetail          `protobuf:"bytes,3,opt,name=courseDetail,proto3" json:"courseDetail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseDetailResponse) Reset() {
	*x = GetCourseDetailResponse{}
	mi := &file_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseDetailResponse) ProtoMessage() {}

func (x *GetCourseDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseDetailResponse.ProtoReflect.Descriptor instead.
func (*GetCourseDetailResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseDetailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCourseDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCourseDetailResponse) GetCourseDetail() *CourseDetail {
	if x != nil {
		return x.CourseDetail
	}
	return nil
}

type GetCategoryTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryTreeRequest) Reset() {
	*x = GetCategoryTreeRequest{}
	mi := &file_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTreeRequest) ProtoMessage() {}

func (x *GetCategoryTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTreeRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryTreeRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{4}
}

type GetCategoryTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List          []*CategoryInfo        `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryTreeResponse) Reset() {
	*x = GetCategoryTreeResponse{}
	mi := &file_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTreeResponse) ProtoMessage() {}

func (x *GetCategoryTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTreeResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryTreeResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{5}
}

func (x *GetCategoryTreeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCategoryTreeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCategoryTreeResponse) GetList() []*CategoryInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 创建课程
type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	TeacherId     int64                  `protobuf:"varint,6,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CreateCourseRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateCourseRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateCourseRequest) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CourseId      int64                  `protobuf:"varint,3,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCourseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCourseResponse) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// 更新课程
type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	CategoryId    int64                  `protobuf:"varint,6,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCourseRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *UpdateCourseRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateCourseRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCourseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 上传视频
type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=videoUrl,proto3" json:"videoUrl,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	IsFree        int32                  `protobuf:"varint,5,opt,name=isFree,proto3" json:"isFree,omitempty"`
	ChapterId     int64                  `protobuf:"varint,6,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{10}
}

func (x *UploadVideoRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *UploadVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *UploadVideoRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UploadVideoRequest) GetIsFree() int32 {
	if x != nil {
		return x.IsFree
	}
	return 0
}

func (x *UploadVideoRequest) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VideoId       int64                  `protobuf:"varint,3,opt,name=videoId,proto3" json:"videoId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_course_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{11}
}

func (x *UploadVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadVideoResponse) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

// 获取课程视频列表
type GetCourseVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseVideosRequest) Reset() {
	*x = GetCourseVideosRequest{}
	mi := &file_course_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseVideosRequest) ProtoMessage() {}

func (x *GetCourseVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseVideosRequest.ProtoReflect.Descriptor instead.
func (*GetCourseVideosRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{12}
}

func (x *GetCourseVideosRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type GetCourseVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Videos        []*VideoInfo           `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseVideosResponse) Reset() {
	*x = GetCourseVideosResponse{}
	mi := &file_course_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseVideosResponse) ProtoMessage() {}

func (x *GetCourseVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseVideosResponse.ProtoReflect.Descriptor instead.
func (*GetCourseVideosResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{13}
}

func (x *GetCourseVideosResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCourseVideosResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCourseVideosResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 创建章节
type CreateChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterRequest) Reset() {
	*x = CreateChapterRequest{}
	mi := &file_course_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterRequest) ProtoMessage() {}

func (x *CreateChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterRequest.ProtoReflect.Descriptor instead.
func (*CreateChapterRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{14}
}

func (x *CreateChapterRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CreateChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChapterRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ChapterId     int64                  `protobuf:"varint,3,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterResponse) Reset() {
	*x = CreateChapterResponse{}
	mi := &file_course_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterResponse) ProtoMessage() {}

func (x *CreateChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterResponse.ProtoReflect.Descriptor instead.
func (*CreateChapterResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{15}
}

func (x *CreateChapterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateChapterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateChapterResponse) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

// 更新课程状态（管理员审核）
type UpdateCourseStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0-待审核 1-已上架 2-已下架
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseStatusRequest) Reset() {
	*x = UpdateCourseStatusRequest{}
	mi := &file_course_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseStatusRequest) ProtoMessage() {}

func (x *UpdateCourseStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseStatusRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCourseStatusRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *UpdateCourseStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateCourseStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseStatusResponse) Reset() {
	*x = UpdateCourseStatusResponse{}
	mi := &file_course_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseStatusResponse) ProtoMessage() {}

func (x *UpdateCourseStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseStatusResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCourseStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateCourseStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 分类管理
type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_course_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCategoryRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_course_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{19}
}

func (x *CreateCategoryResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCategoryResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_course_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_course_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateCategoryResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_course_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_course_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCategoryResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CourseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	TeacherId     int64                  `protobuf:"varint,6,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice float64                `protobuf:"fixed64,8,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	StudentCount  int32                  `protobuf:"varint,9,opt,name=studentCount,proto3" json:"studentCount,omitempty"`
	LessonCount   int32                  `protobuf:"varint,10,opt,name=lessonCount,proto3" json:"lessonCount,omitempty"`
	Duration      int32                  `protobuf:"varint,11,opt,name=duration,proto3" json:"duration,omitempty"`
	Level         int32                  `protobuf:"varint,12,opt,name=level,proto3" json:"level,omitempty"`
	Status        int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"` // 0-待审核 1-已上架 2-已下架
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseInfo) Reset() {
	*x = CourseInfo{}
	mi := &file_course_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseInfo) ProtoMessage() {}

func (x *CourseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseInfo.ProtoReflect.Descriptor instead.
func (*CourseInfo) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{24}
}

func (x *CourseInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CourseInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseInfo) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CourseInfo) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CourseInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CourseInfo) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *CourseInfo) GetStudentCount() int32 {
	if x != nil {
		return x.StudentCount
	}
	return 0
}

func (x *CourseInfo) GetLessonCount() int32 {
	if x != nil {
		return x.LessonCount
	}
	return 0
}

func (x *CourseInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CourseInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CourseInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CourseDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseInfo    *CourseInfo            `protobuf:"bytes,1,opt,name=courseInfo,proto3" json:"courseInfo,omitempty"`
	Chapters      []*ChapterInfo         `protobuf:"bytes,2,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Teacher       *TeacherInfo           `protobuf:"bytes,3,opt,name=teacher,proto3" json:"teacher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDetail) Reset() {
	*x = CourseDetail{}
	mi := &file_course_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDetail) ProtoMessage() {}

func (x *CourseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDetail.ProtoReflect.Descriptor instead.
func (*CourseDetail) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{25}
}

func (x *CourseDetail) GetCourseInfo() *CourseInfo {
	if x != nil {
		return x.CourseInfo
	}
	return nil
}

func (x *CourseDetail) GetChapters() []*ChapterInfo {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *CourseDetail) GetTeacher() *TeacherInfo {
	if x != nil {
		return x.Teacher
	}
	return nil
}

type ChapterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Videos        []*VideoInfo           `protobuf:"bytes,4,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterInfo) Reset() {
	*x = ChapterInfo{}
	mi := &file_course_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterInfo) ProtoMessage() {}

func (x *ChapterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterInfo.ProtoReflect.Descriptor instead.
func (*ChapterInfo) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{26}
}

func (x *ChapterInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChapterInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChapterInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ChapterInfo) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=videoUrl,proto3" json:"videoUrl,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	IsFree        int32                  `protobuf:"varint,6,opt,name=isFree,proto3" json:"isFree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_course_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{27}
}

func (x *VideoInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoInfo) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *VideoInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *VideoInfo) GetIsFree() int32 {
	if x != nil {
		return x.IsFree
	}
	return 0
}

type TeacherInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherInfo) Reset() {
	*x = TeacherInfo{}
	mi := &file_course_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherInfo) ProtoMessage() {}

func (x *TeacherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherInfo.ProtoReflect.Descriptor instead.
func (*TeacherInfo) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{28}
}

func (x *TeacherInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TeacherInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TeacherInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TeacherInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Children      []*CategoryInfo        `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	CourseCount   int32                  `protobuf:"varint,5,opt,name=courseCount,proto3" json:"courseCount,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_course_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{29}
}

func (x *CategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CategoryInfo) GetChildren() []*CategoryInfo {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *CategoryInfo) GetCourseCount() int32 {
	if x != nil {
		return x.CourseCount
	}
	return 0
}

func (x *CategoryInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// 删除课程
type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	TeacherId     int64                  `protobuf:"varint,2,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_course_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *DeleteCourseRequest) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_course_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteCourseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取视频播放URL
type GetVideoPlayURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoPlayURLRequest) Reset() {
	*x = GetVideoPlayURLRequest{}
	mi := &file_course_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoPlayURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoPlayURLRequest) ProtoMessage() {}

func (x *GetVideoPlayURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoPlayURLRequest.ProtoReflect.Descriptor instead.
func (*GetVideoPlayURLRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{32}
}

func (x *GetVideoPlayURLRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetVideoPlayURLRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetVideoPlayURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PlayUrl       string                 `protobuf:"bytes,3,opt,name=playUrl,proto3" json:"playUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoPlayURLResponse) Reset() {
	*x = GetVideoPlayURLResponse{}
	mi := &file_course_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoPlayURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoPlayURLResponse) ProtoMessage() {}

func (x *GetVideoPlayURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoPlayURLResponse.ProtoReflect.Descriptor instead.
func (*GetVideoPlayURLResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{33}
}

func (x *GetVideoPlayURLResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVideoPlayURLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVideoPlayURLResponse) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

var File_course_proto protoreflect.FileDescriptor

const file_course_proto_rawDesc = "" +
	"\n" +
	"\fcourse.proto\x12\ageekedu\"l\n" +
	"\x14GetCourseListRequest\x12\x18\n" +
	"\apageNum\x18\x01 \x01(\x05R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\x03R\n" +
	"categoryId\"\x84\x01\n" +
	"\x15GetCourseListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04list\x18\x03 \x03(\v2\x13.geekedu.CourseInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"4\n" +
	"\x16GetCourseDetailRequest\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x03R\bcourseId\"\x82\x01\n" +
	"\x17GetCourseDetailResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\fcourseDetail\x18\x03 \x01(\v2\x15.geekedu.CourseDetailR\fcourseDetail\"\x18\n" +
	"\x16GetCategoryTreeRequest\"r\n" +
	"\x17GetCategoryTreeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04list\x18\x03 \x03(\v2\x15.geekedu.CategoryInfoR\x04list\"\xbd\x01\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcoverUrl\x18\x03 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x1c\n" +
	"\tteacherId\x18\x06 \x01(\x03R\tteacherId\"`\n" +
	"\x14CreateCourseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bcourseId\x18\x03 \x01(\x03R\bcourseId\"\xbb\x01\n" +
	"\x13UpdateCourseRequest\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcoverUrl\x18\x04 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x06 \x01(\x03R\n" +
	"categoryId\"D\n" +
	"\x14UpdateCourseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb4\x01\n" +
	"\x12UploadVideoRequest\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bvideoUrl\x18\x03 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x16\n" +
	"\x06isFree\x18\x05 \x01(\x05R\x06isFree\x12\x1c\n" +
	"\tchapterId\x18\x06 \x01(\x03R\tchapterId\"]\n" +
	"\x13UploadVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\avideoId\x18\x03 \x01(\x03R\avideoId\"4\n" +
	"\x16GetCourseVideosRequest\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x03R\bcourseId\"s\n" +
	"\x17GetCourseVideosResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x06videos\x18\x03 \x03(\v2\x12.geekedu.VideoInfoR\x06videos\"\\\n" +
	"\x14CreateChapterRequest\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"c\n" +
	"\x15CreateChapterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tchapterId\x18\x03 \x01(\x03R\tchapterId\"O\n" +
	"\x19UpdateCourseStatusRequest\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x03R\bcourseId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"J\n" +
	"\x1aUpdateCourseStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bparentId\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"f\n" +
	"\x16CreateCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\x03R\n" +
	"categoryId\"_\n" +
	"\x15UpdateCategoryRequest\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"F\n" +
	"\x16UpdateCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x15DeleteCategoryRequest\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\"F\n" +
	"\x16DeleteCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf4\x02\n" +
	"\n" +
	"CourseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x1c\n" +
	"\tteacherId\x18\x06 \x01(\x03R\tteacherId\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12$\n" +
	"\roriginalPrice\x18\b \x01(\x01R\roriginalPrice\x12\"\n" +
	"\fstudentCount\x18\t \x01(\x05R\fstudentCount\x12 \n" +
	"\vlessonCount\x18\n" +
	" \x01(\x05R\vlessonCount\x12\x1a\n" +
	"\bduration\x18\v \x01(\x05R\bduration\x12\x14\n" +
	"\x05level\x18\f \x01(\x05R\x05level\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\"\xa5\x01\n" +
	"\fCourseDetail\x123\n" +
	"\n" +
	"courseInfo\x18\x01 \x01(\v2\x13.geekedu.CourseInfoR\n" +
	"courseInfo\x120\n" +
	"\bchapters\x18\x02 \x03(\v2\x14.geekedu.ChapterInfoR\bchapters\x12.\n" +
	"\ateacher\x18\x03 \x01(\v2\x14.geekedu.TeacherInfoR\ateacher\"s\n" +
	"\vChapterInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\x12*\n" +
	"\x06videos\x18\x04 \x03(\v2\x12.geekedu.VideoInfoR\x06videos\"\x97\x01\n" +
	"\tVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x1a\n" +
	"\bvideoUrl\x18\x04 \x01(\tR\bvideoUrl\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x16\n" +
	"\x06isFree\x18\x06 \x01(\x05R\x06isFree\"m\n" +
	"\vTeacherInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\xb7\x01\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bparentId\x18\x03 \x01(\x03R\bparentId\x121\n" +
	"\bchildren\x18\x04 \x03(\v2\x15.geekedu.CategoryInfoR\bchildren\x12 \n" +
	"\vcourseCount\x18\x05 \x01(\x05R\vcourseCount\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"O\n" +
	"\x13DeleteCourseRequest\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x03R\bcourseId\x12\x1c\n" +
	"\tteacherId\x18\x02 \x01(\x03R\tteacherId\"D\n" +
	"\x14DeleteCourseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x16GetVideoPlayURLRequest\x12\x18\n" +
	"\avideoId\x18\x01 \x01(\x03R\avideoId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"a\n" +
	"\x17GetVideoPlayURLResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aplayUrl\x18\x03 \x01(\tR\aplayUrl2\x90\t\n" +
	"\rCourseService\x12N\n" +
	"\rGetCourseList\x12\x1d.geekedu.GetCourseListRequest\x1a\x1e.geekedu.GetCourseListResponse\x12T\n" +
	"\x0fGetCourseDetail\x12\x1f.geekedu.GetCourseDetailRequest\x1a .geekedu.GetCourseDetailResponse\x12T\n" +
	"\x0fGetCategoryTree\x12\x1f.geekedu.GetCategoryTreeRequest\x1a .geekedu.GetCategoryTreeResponse\x12T\n" +
	"\x0fGetVideoPlayURL\x12\x1f.geekedu.GetVideoPlayURLRequest\x1a .geekedu.GetVideoPlayURLResponse\x12K\n" +
	"\fCreateCourse\x12\x1c.geekedu.CreateCourseRequest\x1a\x1d.geekedu.CreateCourseResponse\x12K\n" +
	"\fUpdateCourse\x12\x1c.geekedu.UpdateCourseRequest\x1a\x1d.geekedu.UpdateCourseResponse\x12K\n" +
	"\fDeleteCourse\x12\x1c.geekedu.DeleteCourseRequest\x1a\x1d.geekedu.DeleteCourseResponse\x12H\n" +
	"\vUploadVideo\x12\x1b.geekedu.UploadVideoRequest\x1a\x1c.geekedu.UploadVideoResponse\x12T\n" +
	"\x0fGetCourseVideos\x12\x1f.geekedu.GetCourseVideosRequest\x1a .geekedu.GetCourseVideosResponse\x12N\n" +
	"\rCreateChapter\x12\x1d.geekedu.CreateChapterRequest\x1a\x1e.geekedu.CreateChapterResponse\x12]\n" +
	"\x12UpdateCourseStatus\x12\".geekedu.UpdateCourseStatusRequest\x1a#.geekedu.UpdateCourseStatusResponse\x12Q\n" +
	"\x0eCreateCategory\x12\x1e.geekedu.CreateCategoryRequest\x1a\x1f.geekedu.CreateCategoryResponse\x12Q\n" +
	"\x0eUpdateCategory\x12\x1e.geekedu.UpdateCategoryRequest\x1a\x1f.geekedu.UpdateCategoryResponse\x12Q\n" +
	"\x0eDeleteCategory\x12\x1e.geekedu.DeleteCategoryRequest\x1a\x1f.geekedu.DeleteCategoryResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_course_proto_rawDescOnce sync.Once
	file_course_proto_rawDescData []byte
)

func file_course_proto_rawDescGZIP() []byte {
	file_course_proto_rawDescOnce.Do(func() {
		file_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)))
	})
	return file_course_proto_rawDescData
}

var file_course_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_course_proto_goTypes = []any{
	(*GetCourseListRequest)(nil),       // 0: geekedu.GetCourseListRequest
	(*GetCourseListResponse)(nil),      // 1: geekedu.GetCourseListResponse
	(*GetCourseDetailRequest)(nil),     // 2: geekedu.GetCourseDetailRequest
	(*GetCourseDetailResponse)(nil),    // 3: geekedu.GetCourseDetailResponse
	(*GetCategoryTreeRequest)(nil),     // 4: geekedu.GetCategoryTreeRequest
	(*GetCategoryTreeResponse)(nil),    // 5: geekedu.GetCategoryTreeResponse
	(*CreateCourseRequest)(nil),        // 6: geekedu.CreateCourseRequest
	(*CreateCourseResponse)(nil),       // 7: geekedu.CreateCourseResponse
	(*UpdateCourseRequest)(nil),        // 8: geekedu.UpdateCourseRequest
	(*UpdateCourseResponse)(nil),       // 9: geekedu.UpdateCourseResponse
	(*UploadVideoRequest)(nil),         // 10: geekedu.UploadVideoRequest
	(*UploadVideoResponse)(nil),        // 11: geekedu.UploadVideoResponse
	(*GetCourseVideosRequest)(nil),     // 12: geekedu.GetCourseVideosRequest
	(*GetCourseVideosResponse)(nil),    // 13: geekedu.GetCourseVideosResponse
	(*CreateChapterRequest)(nil),       // 14: geekedu.CreateChapterRequest
	(*CreateChapterResponse)(nil),      // 15: geekedu.CreateChapterResponse
	(*UpdateCourseStatusRequest)(nil),  // 16: geekedu.UpdateCourseStatusRequest
	(*UpdateCourseStatusResponse)(nil), // 17: geekedu.UpdateCourseStatusResponse
	(*CreateCategoryRequest)(nil),      // 18: geekedu.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),     // 19: geekedu.CreateCategoryResponse
	(*UpdateCategoryRequest)(nil),      // 20: geekedu.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),     // 21: geekedu.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),      // 22: geekedu.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),     // 23: geekedu.DeleteCategoryResponse
	(*CourseInfo)(nil),                 // 24: geekedu.CourseInfo
	(*CourseDetail)(nil),               // 25: geekedu.CourseDetail
	(*ChapterInfo)(nil),                // 26: geekedu.ChapterInfo
	(*VideoInfo)(nil),                  // 27: geekedu.VideoInfo
	(*TeacherInfo)(nil),                // 28: geekedu.TeacherInfo
	(*CategoryInfo)(nil),               // 29: geekedu.CategoryInfo
	(*DeleteCourseRequest)(nil),        // 30: geekedu.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),       // 31: geekedu.DeleteCourseResponse
	(*GetVideoPlayURLRequest)(nil),     // 32: geekedu.GetVideoPlayURLRequest
	(*GetVideoPlayURLResponse)(nil),    // 33: geekedu.GetVideoPlayURLResponse
}
var file_course_proto_depIdxs = []int32{
	24, // 0: geekedu.GetCourseListResponse.list:type_name -> geekedu.CourseInfo
	25, // 1: geekedu.GetCourseDetailResponse.courseDetail:type_name -> geekedu.CourseDetail
	29, // 2: geekedu.GetCategoryTreeResponse.list:type_name -> geekedu.CategoryInfo
	27, // 3: geekedu.GetCourseVideosResponse.videos:type_name -> geekedu.VideoInfo
	24, // 4: geekedu.CourseDetail.courseInfo:type_name -> geekedu.CourseInfo
	26, // 5: geekedu.CourseDetail.chapters:type_name -> geekedu.ChapterInfo
	28, // 6: geekedu.CourseDetail.teacher:type_name -> geekedu.TeacherInfo
	27, // 7: geekedu.ChapterInfo.videos:type_name -> geekedu.VideoInfo
	29, // 8: geekedu.CategoryInfo.children:type_name -> geekedu.CategoryInfo
	0,  // 9: geekedu.CourseService.GetCourseList:input_type -> geekedu.GetCourseListRequest
	2,  // 10: geekedu.CourseService.GetCourseDetail:input_type -> geekedu.GetCourseDetailRequest
	4,  // 11: geekedu.CourseService.GetCategoryTree:input_type -> geekedu.GetCategoryTreeRequest
	32, // 12: geekedu.CourseService.GetVideoPlayURL:input_type -> geekedu.GetVideoPlayURLRequest
	6,  // 13: geekedu.CourseService.CreateCourse:input_type -> geekedu.CreateCourseRequest
	8,  // 14: geekedu.CourseService.UpdateCourse:input_type -> geekedu.UpdateCourseRequest
	30, // 15: geekedu.CourseService.DeleteCourse:input_type -> geekedu.DeleteCourseRequest
	10, // 16: geekedu.CourseService.UploadVideo:input_type -> geekedu.UploadVideoRequest
	12, // 17: geekedu.CourseService.GetCourseVideos:input_type -> geekedu.GetCourseVideosRequest
	14, // 18: geekedu.CourseService.CreateChapter:input_type -> geekedu.CreateChapterRequest
	16, // 19: geekedu.CourseService.UpdateCourseStatus:input_type -> geekedu.UpdateCourseStatusRequest
	18, // 20: geekedu.CourseService.CreateCategory:input_type -> geekedu.CreateCategoryRequest
	20, // 21: geekedu.CourseService.UpdateCategory:input_type -> geekedu.UpdateCategoryRequest
	22, // 22: geekedu.CourseService.DeleteCategory:input_type -> geekedu.DeleteCategoryRequest
	1,  // 23: geekedu.CourseService.GetCourseList:output_type -> geekedu.GetCourseListResponse
	3,  // 24: geekedu.CourseService.GetCourseDetail:output_type -> geekedu.GetCourseDetailResponse
	5,  // 25: geekedu.CourseService.GetCategoryTree:output_type -> geekedu.GetCategoryTreeResponse
	33, // 26: geekedu.CourseService.GetVideoPlayURL:output_type -> geekedu.GetVideoPlayURLResponse
	7,  // 27: geekedu.CourseService.CreateCourse:output_type -> geekedu.CreateCourseResponse
	9,  // 28: geekedu.CourseService.UpdateCourse:output_type -> geekedu.UpdateCourseResponse
	31, // 29: geekedu.CourseService.DeleteCourse:output_type -> geekedu.DeleteCourseResponse
	11, // 30: geekedu.CourseService.UploadVideo:output_type -> geekedu.UploadVideoResponse
	13, // 31: geekedu.CourseService.GetCourseVideos:output_type -> geekedu.GetCourseVideosResponse
	15, // 32: geekedu.CourseService.CreateChapter:output_type -> geekedu.CreateChapterResponse
	17, // 33: geekedu.CourseService.UpdateCourseStatus:output_type -> geekedu.UpdateCourseStatusResponse
	19, // 34: geekedu.CourseService.CreateCategory:output_type -> geekedu.CreateCategoryResponse
	21, // 35: geekedu.CourseService.UpdateCategory:output_type -> geekedu.UpdateCategoryResponse
	23, // 36: geekedu.CourseService.DeleteCategory:output_type -> geekedu.DeleteCategoryResponse
	23, // [23:37] is the sub-list for method output_type
	9,  // [9:23] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_course_proto_init() }
func file_course_proto_init() {
	if File_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_proto_goTypes,
		DependencyIndexes: file_course_proto_depIdxs,
		MessageInfos:      file_course_proto_msgTypes,
	}.Build()
	File_course_proto = out.File
	file_course_proto_goTypes = nil
	file_course_proto_depIdxs = nil
}
